import Head from "next/head";
import App from "../Components/App";
import Navbar from "../Components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LaptopQuery</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <App />
      </div>
    </div>
  );
}
