import Head from "next/head";
import App from "../Components/App";
export async function getStaticProps() {
  let url = "http://localhost:1337/api/posts?populate=*";
  let res = await fetch(url);
  let mydata = await res.json();

  return {
    props: {
      data: mydata.data,
    },
  };
}
export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>LaptopQuery</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <App data={data}/>
      </div>
    </div>
  );
}
